-- Create tables

CREATE TABLE User (
	UserID VARCHAR(100) NOT NULL,
	Location VARCHAR(50) DEFAULT NULL,
	Country VARCHAR(50) DEFAULT NULL,
	PRIMARY KEY(UserID)
);

CREATE TABLE Item (
	ItemID INTEGER NOT NULL,
	Name VARCHAR(150) NOT NULL,
	UserID VARCHAR(100) NOT NULL,
	Started TIMESTAMP NOT NULL,
	Ends TIMESTAMP NOT NULL,
	First_Bid DECIMAL(8,2) NOT NULL,
	BuyPrice DECIMAL(8,2) DEFAULT NULL,
	Currently DECIMAL(8,2) NOT NULL,
	Latitude DECIMAL(10,6) NOT NULL,
	Longitude DECIMAL(10,6) NOT NULL,
	DESCRIPTION VARCHAR(4000),
	PRIMARY KEY(ItemID),
	FOREIGN KEY(UserID) REFERENCES User(UserID)
);

CREATE TABLE SellerRate (
	UserID VARCHAR(100) NOT NULL,
	Rating INTEGER NOT NULL,
	PRIMARY KEY(UserID),
	FOREIGN KEY(UserID) REFERENCES User(UserID)
);

CREATE TABLE BidderRate (
	UserID VARCHAR(100) NOT NULL,
	Rating INTEGER NOT NULL,
	PRIMARY KEY(UserID),
	FOREIGN KEY(UserID) REFERENCES User(UserID)
);

CREATE TABLE Category(
	CategoryID INTEGER NOT NULL,
	Category VARCHAR(100) NOT NULL,
	PRIMARY KEY(CategoryID)
);

CREATE TABLE ItemCategory (
	ItemID INTEGER NOT NULL,
	CategoryID INTEGER NOT NULL,
	PRIMARY KEY(ItemID, CategoryID),
	FOREIGN KEY(ItemID) REFERENCES Item(ItemID),
	FOREIGN KEY(CategoryID) REFERENCES Category(CategoryID)
);

CREATE TABLE Bid (
	ItemID INTEGER NOT NULL,
	UserID VARCHAR(100) NOT NULL,
	Time TIMESTAMP NOT NULL,
	Amount DECIMAL(8,2) NOT NULL,
	PRIMARY KEY(ItemID, UserID),
	FOREIGN KEY(ItemID) REFERENCES Item(ItemID),
	FOREIGN KEY(UserID) REFERENCES User(UserID)
);
